[2024-11-15T06:29:53.452+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-11-15T06:29:53.501+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: email_pipeline.run_result_script scheduled__2024-11-15T06:20:00+00:00 [queued]>
[2024-11-15T06:29:53.516+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: email_pipeline.run_result_script scheduled__2024-11-15T06:20:00+00:00 [queued]>
[2024-11-15T06:29:53.516+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 2
[2024-11-15T06:29:53.549+0000] {taskinstance.py:2889} INFO - Executing <Task(BashOperator): run_result_script> on 2024-11-15 06:20:00+00:00
[2024-11-15T06:29:53.562+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=76) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-11-15T06:29:53.566+0000] {standard_task_runner.py:72} INFO - Started process 77 to run task
[2024-11-15T06:29:53.568+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'email_pipeline', 'run_result_script', 'scheduled__2024-11-15T06:20:00+00:00', '--job-id', '3', '--raw', '--subdir', 'DAGS_FOLDER/workflow.py', '--cfg-path', '/tmp/tmpjowaln5m']
[2024-11-15T06:29:53.569+0000] {standard_task_runner.py:105} INFO - Job 3: Subtask run_result_script
[2024-11-15T06:29:53.694+0000] {task_command.py:467} INFO - Running <TaskInstance: email_pipeline.run_result_script scheduled__2024-11-15T06:20:00+00:00 [running]> on host d7073c96926f
[2024-11-15T06:29:53.858+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='email_pipeline' AIRFLOW_CTX_TASK_ID='run_result_script' AIRFLOW_CTX_EXECUTION_DATE='2024-11-15T06:20:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-11-15T06:20:00+00:00'
[2024-11-15T06:29:53.860+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-11-15T06:29:53.937+0000] {subprocess.py:78} INFO - Tmp dir root location: /tmp
[2024-11-15T06:29:53.939+0000] {subprocess.py:88} INFO - Running command: ['/usr/bin/bash', '-c', 'python /opt/***/dags/result.py']
[2024-11-15T06:29:53.955+0000] {subprocess.py:99} INFO - Output:
[2024-11-15T06:29:57.758+0000] {subprocess.py:106} INFO - Traceback (most recent call last):
[2024-11-15T06:29:57.759+0000] {subprocess.py:106} INFO -   File "/opt/***/dags/result.py", line 5, in <module>
[2024-11-15T06:29:57.760+0000] {subprocess.py:106} INFO -     from pymongo import MongoClient
[2024-11-15T06:29:57.761+0000] {subprocess.py:106} INFO - ModuleNotFoundError: No module named 'pymongo'
[2024-11-15T06:29:57.899+0000] {subprocess.py:110} INFO - Command exited with return code 1
[2024-11-15T06:29:57.912+0000] {taskinstance.py:3311} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 276, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2024-11-15T06:29:57.929+0000] {taskinstance.py:1225} INFO - Marking task as UP_FOR_RETRY. dag_id=email_pipeline, task_id=run_result_script, run_id=scheduled__2024-11-15T06:20:00+00:00, execution_date=20241115T062000, start_date=20241115T062953, end_date=20241115T062957
[2024-11-15T06:29:58.009+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-11-15T06:29:58.011+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 3 for task run_result_script (Bash command failed. The command returned a non-zero exit code 1.; 77)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3005, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3159, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3183, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 276, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2024-11-15T06:29:58.058+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2024-11-15T06:29:58.080+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-11-15T06:29:58.085+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
