[2024-11-15T07:20:00.543+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-11-15T07:20:00.559+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: email_pipeline.run_result_script scheduled__2024-11-15T07:15:00+00:00 [queued]>
[2024-11-15T07:20:00.570+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: email_pipeline.run_result_script scheduled__2024-11-15T07:15:00+00:00 [queued]>
[2024-11-15T07:20:00.571+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 2
[2024-11-15T07:20:00.586+0000] {taskinstance.py:2889} INFO - Executing <Task(BashOperator): run_result_script> on 2024-11-15 07:15:00+00:00
[2024-11-15T07:20:00.595+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'email_pipeline', 'run_result_script', 'scheduled__2024-11-15T07:15:00+00:00', '--job-id', '13', '--raw', '--subdir', 'DAGS_FOLDER/workflow.py', '--cfg-path', '/tmp/tmpuchunr1v']
[2024-11-15T07:20:00.598+0000] {standard_task_runner.py:105} INFO - Job 13: Subtask run_result_script
[2024-11-15T07:20:00.593+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=479) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-11-15T07:20:00.603+0000] {standard_task_runner.py:72} INFO - Started process 480 to run task
[2024-11-15T07:20:00.693+0000] {task_command.py:467} INFO - Running <TaskInstance: email_pipeline.run_result_script scheduled__2024-11-15T07:15:00+00:00 [running]> on host 1d9b6efd6c03
[2024-11-15T07:20:00.792+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='email_pipeline' AIRFLOW_CTX_TASK_ID='run_result_script' AIRFLOW_CTX_EXECUTION_DATE='2024-11-15T07:15:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-11-15T07:15:00+00:00'
[2024-11-15T07:20:00.793+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-11-15T07:20:00.810+0000] {subprocess.py:78} INFO - Tmp dir root location: /tmp
[2024-11-15T07:20:00.811+0000] {subprocess.py:88} INFO - Running command: ['/usr/bin/bash', '-c', 'python /opt/***/dags/result.py']
[2024-11-15T07:20:00.822+0000] {subprocess.py:99} INFO - Output:
[2024-11-15T07:20:07.421+0000] {subprocess.py:110} INFO - Command exited with return code 0
[2024-11-15T07:20:07.450+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-11-15T07:20:07.451+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=email_pipeline, task_id=run_result_script, run_id=scheduled__2024-11-15T07:15:00+00:00, execution_date=20241115T071500, start_date=20241115T072000, end_date=20241115T072007
[2024-11-15T07:20:07.506+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-11-15T07:20:07.520+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-11-15T07:20:07.524+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2024-11-15T07:24:40.852+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-11-15T07:24:40.874+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: email_pipeline.run_result_script scheduled__2024-11-15T07:15:00+00:00 [queued]>
[2024-11-15T07:24:40.887+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: email_pipeline.run_result_script scheduled__2024-11-15T07:15:00+00:00 [queued]>
[2024-11-15T07:24:40.888+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 2
[2024-11-15T07:24:40.910+0000] {taskinstance.py:2889} INFO - Executing <Task(BashOperator): run_result_script> on 2024-11-15 07:15:00+00:00
[2024-11-15T07:24:40.921+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=75) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-11-15T07:24:40.923+0000] {standard_task_runner.py:72} INFO - Started process 76 to run task
[2024-11-15T07:24:40.923+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'email_pipeline', 'run_result_script', 'scheduled__2024-11-15T07:15:00+00:00', '--job-id', '4', '--raw', '--subdir', 'DAGS_FOLDER/workflow.py', '--cfg-path', '/tmp/tmpe9e39hfa']
[2024-11-15T07:24:40.925+0000] {standard_task_runner.py:105} INFO - Job 4: Subtask run_result_script
[2024-11-15T07:24:40.988+0000] {task_command.py:467} INFO - Running <TaskInstance: email_pipeline.run_result_script scheduled__2024-11-15T07:15:00+00:00 [running]> on host d4c24de2763c
[2024-11-15T07:24:41.089+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='email_pipeline' AIRFLOW_CTX_TASK_ID='run_result_script' AIRFLOW_CTX_EXECUTION_DATE='2024-11-15T07:15:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-11-15T07:15:00+00:00'
[2024-11-15T07:24:41.090+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-11-15T07:24:41.150+0000] {subprocess.py:78} INFO - Tmp dir root location: /tmp
[2024-11-15T07:24:41.151+0000] {subprocess.py:88} INFO - Running command: ['/usr/bin/bash', '-c', 'python /opt/***/dags/result.py']
[2024-11-15T07:24:41.166+0000] {subprocess.py:99} INFO - Output:
[2024-11-15T07:25:21.520+0000] {subprocess.py:106} INFO - Traceback (most recent call last):
[2024-11-15T07:25:21.521+0000] {subprocess.py:106} INFO -   File "/opt/***/dags/result.py", line 41, in <module>
[2024-11-15T07:25:21.522+0000] {subprocess.py:106} INFO -     if not collection.find_one({"message": row['message']}):
[2024-11-15T07:25:21.522+0000] {subprocess.py:106} INFO -            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2024-11-15T07:25:21.523+0000] {subprocess.py:106} INFO -   File "/home/***/.local/lib/python3.12/site-packages/pymongo/collection.py", line 1508, in find_one
[2024-11-15T07:25:21.523+0000] {subprocess.py:106} INFO -     for result in cursor.limit(-1):
[2024-11-15T07:25:21.524+0000] {subprocess.py:106} INFO -                   ^^^^^^^^^^^^^^^^
[2024-11-15T07:25:21.525+0000] {subprocess.py:106} INFO -   File "/home/***/.local/lib/python3.12/site-packages/pymongo/cursor.py", line 1262, in next
[2024-11-15T07:25:21.525+0000] {subprocess.py:106} INFO -     if len(self.__data) or self._refresh():
[2024-11-15T07:25:21.525+0000] {subprocess.py:106} INFO -                            ^^^^^^^^^^^^^^^
[2024-11-15T07:25:21.526+0000] {subprocess.py:106} INFO -   File "/home/***/.local/lib/python3.12/site-packages/pymongo/cursor.py", line 1153, in _refresh
[2024-11-15T07:25:21.527+0000] {subprocess.py:106} INFO -     self.__session = self.__collection.database.client._ensure_session()
[2024-11-15T07:25:21.528+0000] {subprocess.py:106} INFO -                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2024-11-15T07:25:21.529+0000] {subprocess.py:106} INFO -   File "/home/***/.local/lib/python3.12/site-packages/pymongo/mongo_client.py", line 1868, in _ensure_session
[2024-11-15T07:25:21.530+0000] {subprocess.py:106} INFO -     return self.__start_session(True, causal_consistency=False)
[2024-11-15T07:25:21.530+0000] {subprocess.py:106} INFO -            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2024-11-15T07:25:21.531+0000] {subprocess.py:106} INFO -   File "/home/***/.local/lib/python3.12/site-packages/pymongo/mongo_client.py", line 1811, in __start_session
[2024-11-15T07:25:21.531+0000] {subprocess.py:106} INFO -     self._topology._check_implicit_session_support()
[2024-11-15T07:25:21.532+0000] {subprocess.py:106} INFO -   File "/home/***/.local/lib/python3.12/site-packages/pymongo/topology.py", line 583, in _check_implicit_session_support
[2024-11-15T07:25:21.533+0000] {subprocess.py:106} INFO -     self._check_session_support()
[2024-11-15T07:25:21.534+0000] {subprocess.py:106} INFO -   File "/home/***/.local/lib/python3.12/site-packages/pymongo/topology.py", line 599, in _check_session_support
[2024-11-15T07:25:21.534+0000] {subprocess.py:106} INFO -     self._select_servers_loop(
[2024-11-15T07:25:21.535+0000] {subprocess.py:106} INFO -   File "/home/***/.local/lib/python3.12/site-packages/pymongo/topology.py", line 269, in _select_servers_loop
[2024-11-15T07:25:21.535+0000] {subprocess.py:106} INFO -     raise ServerSelectionTimeoutError(
[2024-11-15T07:25:21.536+0000] {subprocess.py:106} INFO - pymongo.errors.ServerSelectionTimeoutError: localhost:27017: [Errno 111] Connection refused, Timeout: 30s, Topology Description: <TopologyDescription id: 6736f73dda9e77b4548104f5, topology_type: Unknown, servers: [<ServerDescription ('localhost', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('localhost:27017: [Errno 111] Connection refused')>]>
[2024-11-15T07:25:22.241+0000] {subprocess.py:110} INFO - Command exited with return code 1
[2024-11-15T07:25:22.255+0000] {taskinstance.py:3311} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 276, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2024-11-15T07:25:22.265+0000] {taskinstance.py:1225} INFO - Marking task as UP_FOR_RETRY. dag_id=email_pipeline, task_id=run_result_script, run_id=scheduled__2024-11-15T07:15:00+00:00, execution_date=20241115T071500, start_date=20241115T072440, end_date=20241115T072522
[2024-11-15T07:25:22.287+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-11-15T07:25:22.288+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 4 for task run_result_script (Bash command failed. The command returned a non-zero exit code 1.; 76)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3005, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3159, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3183, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 276, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2024-11-15T07:25:22.312+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2024-11-15T07:25:22.333+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-11-15T07:25:22.339+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
